apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-role
rules:
  - apiGroups: [""]
    verbs: ["get", "watch", "list"]
    resources:
     - nodes/metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-crb
subjects:
  - kind: ServiceAccount
    name: monitoring
    apiGroup: ""
    namespace: homework
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: monitoring-role


  