apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: homework
data:
  hello.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Hello, World!</title>
    </head>
    <body>
    <h1>Hello, World!</h1>
    </body>
    </html>
  