apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 55M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-sc
  local:
    path: /pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: homework
              operator: In
              values:
                - "true"