apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: homework
spec:
  volumes:
    - name: config-volume
      configMap:
        name: nginx-conf
    - name: html
      emptyDir:
        sizeLimit: 50M
  initContainers:
    - name: init
      image: busybox:1.28
      volumeMounts:
        - mountPath: /init
          name: html
      command: ['wget', '-O', '/init/index.html','http://ya.ru']
  containers:
    - name: test-pod
      image: nginx:latest
      volumeMounts:
        - mountPath: /homework
          name: html
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
      ports:
        - containerPort: 8000
          protocol: TCP



